2016-03-31 10:42:47,352 - knowledge_logger - main.py-handle-api- : (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`compfie_creativegroups_1`.`tbl_assigned_compliances`, CONSTRAINT `fk_assigned_compliances_countries` FOREIGN KEY (`country_id`) REFERENCES `tbl_countries` (`country_id`))')
2016-03-31 10:42:47,353 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 131, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 185, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/technocontroller.py", line 42, in process_techno_request
    return update_client_group(db, request_frame, session_user)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/technomastercontroller.py", line 165, in update_client_group
    )
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 3957, in replicate_client_countries_and_domains
    delete_domains_query = "delete from tbl_domains"
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`compfie_creativegroups_1`.`tbl_assigned_compliances`, CONSTRAINT `fk_assigned_compliances_countries` FOREIGN KEY (`country_id`) REFERENCES `tbl_countries` (`country_id`))')

2016-03-31 10:42:52,398 - knowledge_logger - main.py-handle-api- : (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`compfie_creativegroups_1`.`tbl_assigned_compliances`, CONSTRAINT `fk_assigned_compliances_countries` FOREIGN KEY (`country_id`) REFERENCES `tbl_countries` (`country_id`))')
2016-03-31 10:42:52,398 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 131, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 185, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/technocontroller.py", line 42, in process_techno_request
    return update_client_group(db, request_frame, session_user)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/technomastercontroller.py", line 165, in update_client_group
    )
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 3957, in replicate_client_countries_and_domains
    delete_domains_query = "delete from tbl_domains"
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`compfie_creativegroups_1`.`tbl_assigned_compliances`, CONSTRAINT `fk_assigned_compliances_countries` FOREIGN KEY (`country_id`) REFERENCES `tbl_countries` (`country_id`))')

2016-03-31 10:44:36,185 - knowledge_logger - main.py-handle-api- : (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`compfie_creativegroups_1`.`tbl_assigned_compliances`, CONSTRAINT `fk_assigned_compliances_countries` FOREIGN KEY (`country_id`) REFERENCES `tbl_countries` (`country_id`))')
2016-03-31 10:44:36,186 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 131, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 185, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/technocontroller.py", line 42, in process_techno_request
    return update_client_group(db, request_frame, session_user)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/technomastercontroller.py", line 165, in update_client_group
    )
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 3957, in replicate_client_countries_and_domains
    delete_domains_query = "delete from tbl_domains"
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`compfie_creativegroups_1`.`tbl_assigned_compliances`, CONSTRAINT `fk_assigned_compliances_countries` FOREIGN KEY (`country_id`) REFERENCES `tbl_countries` (`country_id`))')

